import { createAttachment, createNoteWithCategory, saveNoteEmbedding } from "@/src/server/notes/repository";
import { parseCategory } from "@/src/server/notes/category-parser";
import { markEventCompleted, markEventFailed } from "@/src/server/webhook/event-repository";
import { query } from "@/src/server/db";
import { downloadLineContent } from "@/src/server/line/content-client";
import { saveFile } from "@/src/server/storage/file-store";
import { removeFile } from "@/src/server/storage/file-store";
import { createEmbeddingProvider } from "@/src/server/ai/provider-factory";
import { loadConfig } from "@/src/server/config";
import { Readable } from "node:stream";
export async function processWebhookEvent(eventId: string) { const result = await query<Record<string, unknown>>(`SELECT * FROM webhook_events WHERE id = $1`, [eventId]); const event = result.rows[0]; if (!event) throw new Error("Webhook event not found"); let stored: { storagePath: string; originalName: string; mimeType: string; sizeBytes: number; sha256: string } | null = null; try { const payload = event.payload_json as { message?: { type?: string; text?: string; id?: string; fileName?: string }; timestamp?: number; }; const message = payload.message; if (message) { const parsed = parseCategory(message.text ?? ""); if (message.id && ["image", "video", "audio", "file"].includes(message.type ?? "")) { const response = await downloadLineContent(message.id); if (!response.body) throw new Error("LINE content response has no body"); stored = await saveFile(Readable.fromWeb(response.body as never), message.fileName ?? `${message.id}.${message.type}`, response.headers.get("content-type") ?? "application/octet-stream"); } const note = await createNoteWithCategory({ source: "line", contentType: message.type ?? "unknown", textContent: parsed.searchableText || null, categoryName: parsed.categoryName, lineMessageId: message.id ?? null, capturedAt: payload.timestamp ? new Date(payload.timestamp) : new Date() }); if (stored) await createAttachment({ noteId: note.id, lineMessageId: message.id, originalName: stored.originalName, mimeType: stored.mimeType, sizeBytes: stored.sizeBytes, storagePath: stored.storagePath, sha256: stored.sha256 }); if (note.textContent) { try { const provider = createEmbeddingProvider(); const vector = await provider.embedOne(note.textContent); const model = provider.getModelInfo(); await saveNoteEmbedding(note.id, note.textContent, vector, model.provider, model.model); } catch { /* AI is optional; keyword search must continue working. */ } } } await markEventCompleted(eventId); return { ok: true }; } catch (error) { if (stored) await removeFile(stored.storagePath).catch(() => undefined); await markEventFailed(eventId, error instanceof Error ? error.message : "Processing failed", true, loadConfig().maxWebhookAttempts); return { ok: false }; } }
